### ISSUE TITLE
RUN TIME EXCEPTION [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

### ISSUE THREAD

**Issue by UsabilitySpace** [AseemWangoo/services_demo#5]
**When trying to run the app, it shows blank white screen and throws such an error:** 

```
E/flutter (15434): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (15434): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (15434): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (15434): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:92:7)
E/flutter (15434): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:105:4)
E/flutter (15434): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:143:62)
E/flutter (15434): #3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:149:36)
E/flutter (15434): #4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (15434): #5      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:75:35)
E/flutter (15434): #6      main (package:services_demo/main.dart:12:29)
E/flutter (15434): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (15434): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (15434): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (15434): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (15434): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (15434): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (15434): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (15434): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12) 
```

**So, the code of this app won't run properly until services binding is properly initialized.** 

**To archive services binding proper initialization, please change your code here:** 

- main.dart / main () / about line 11

**... by replacing this line:** 

```
await AndroidAlarmManager.initialize();
```

**... by the next two lines:** 

```
WidgetsFlutterBinding.ensureInitialized(); # ensuring services binding proper initialization
await AndroidAlarmManager.initialize(); # now safely initializing AndroidAlarmManager
```

**Comment by AseemWangoo** [comment]
Thanks for the suggestions. Feel free to create a PR ☺️
